### ISSUE TITLE
Error on war deployment

### ISSUE THREAD

**Issue by adelisle** [camunda/camunda-sso-snippets#8]
I am having trouble trying to test the Keycloak integration demo plugin.

I'm a bit of a noob when it comes to maven, however I managed to piece together that the following command might do what I need:
```
mvn wildfly:run
```

However, I'm getting the following error when it comes time to deploy the WAR file and Wildfly shuts down:
```
14:46:50,422 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.module.service."deployment.camunda-webapp-jboss-sso-7.9.0.war".main: org.jboss.msc.service.StartException in service jboss.module.service."deployment.camunda-webapp-jboss-sso-7.9.0.war".main: WFLYSRV0179: Failed to load module: deployment.camunda-webapp-jboss-sso-7.9.0.war
        at org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:116)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.modules.ModuleNotFoundException: org.camunda.bpm.camunda-engine
        at org.jboss.modules.Module.addPaths(Module.java:1266)
        at org.jboss.modules.Module.link(Module.java:1622)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1650)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:299)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:283)
        at org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:93)
        ... 8 more
```

I cannot tell what, if anything, I could be doing wrong.

A little help would be greatly appreciated.

Full log file: [mvn-wilfdly-run.log](https://github.com/camunda/camunda-sso-snippets/files/4099672/mvn-wilfdly-run.log)

**Comment by falko** [comment]
@benhoffmann can you help here?

**Comment by benhoffmann** [comment]
Hi @adelisle,

I think that the snippet does not provide a fully runnable example, but rather focuses on the SSO part. If you are looking for a general getting started guide of how to use Camunda, have a look at https://docs.camunda.org/get-started/ .

Also, the Community Forum at https://forum.camunda.org is a good resource to get answers to all your questions.

Best, Ben

**Comment by adelisle** [comment]
Oh, that's a shame. It read like it was a full demo.
